export const safetyScoreStyles = {
  card: 'overflow-hidden relative group h-full border-white/5',
  bgGradient: 'absolute inset-0 bg-gradient-to-br from-safe/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity',
  svgBg: 'absolute bottom-0 left-0 w-full h-12 text-safe/8',
  header: 'pb-1 pt-4 px-4 flex justify-between items-start',
  title: 'text-text-muted text-[11px] font-medium uppercase tracking-wider',
  iconWrapper: 'p-1.5 bg-safe/10 rounded-lg',
  icon: 'w-3.5 h-3.5 text-safe',
  content: 'relative z-10 px-4 pb-4 pt-1',
  scoreWrapper: 'text-3xl font-extrabold text-white font-outfit',
  maxScore: 'text-lg text-text-muted font-normal',
  trendWrapper: 'flex items-center gap-1.5 mt-1.5',
  trendIcon: 'w-3 h-3 text-safe',
  trendText: 'text-[10px] text-safe font-semibold',
  lastUpdated: 'text-[9px] text-text-muted/60 mt-1',
};
