export const styles = {
  container: 'bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden flex flex-col',
  header: 'p-6 border-b border-gray-100',
  headerContent: 'flex items-center justify-between',
  title: 'text-lg font-bold text-gray-900',
  subtitle: 'text-sm text-gray-500',
  liveWrapper: 'flex items-center gap-2',
  liveIndicator: 'w-2 h-2 bg-emerald-500 rounded-full animate-pulse',
  liveText: 'text-sm text-gray-500 font-semibold',
  list: 'p-6 relative space-y-6 flex-1',
  timelineLine: 'absolute left-9 top-6 bottom-6 w-0.5 bg-gray-100',
  item: 'flex items-start gap-4 relative z-10',
  iconWrapper: 'w-8 h-8 rounded-full border bg-white flex items-center justify-center shadow-sm flex-shrink-0',
  contentWrapper: 'flex-1 min-w-0',
  actionRow: 'flex items-baseline justify-between gap-2',
  actionText: 'text-sm font-semibold text-gray-900',
  location: 'text-xs text-gray-400 mt-1',
  metaRow: 'flex items-center gap-2 mt-2',
  badge: 'text-[10px] font-bold px-2 py-0.5 rounded-full border uppercase tracking-wider',
  time: 'text-xs text-gray-400 whitespace-nowrap'
};
