export const styles = {
  container: 'relative overflow-hidden bg-[#0d1222]/90 border border-gray-800 rounded-3xl p-6 shadow-2xl backdrop-blur-xl flex flex-col justify-between min-h-[360px]',
  glow: 'absolute top-0 right-0 w-[180px] h-[180px] rounded-full bg-blue-500/10 blur-[80px] pointer-events-none',
  header: 'flex items-center gap-3 mb-6',
  iconBox: 'w-10 h-10 rounded-xl bg-gradient-to-br from-blue-500/20 to-indigo-500/20 border border-blue-500/30 flex items-center justify-center text-blue-400',
  title: 'text-lg font-bold text-white tracking-wide',
  content: 'space-y-5 flex-1',
  scoreSection: 'flex items-center justify-between',
  scoreLabel: 'text-sm text-gray-400',
  scoreValue: 'text-2xl font-black text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-emerald-400',
  explanation: 'text-gray-300 text-sm leading-relaxed font-normal bg-gray-900/50 p-4 rounded-xl border border-gray-800/80',
  routeInfo: 'flex items-center justify-between p-3 bg-blue-500/5 rounded-xl border border-blue-500/10',
  routeLabel: 'text-xs text-gray-400',
  routeText: 'text-sm font-semibold text-blue-400',
  confidenceSection: 'space-y-1.5',
  confidenceHeader: 'flex justify-between text-xs text-gray-400 font-medium',
  confidenceBarOuter: 'w-full h-2 bg-gray-800 rounded-full overflow-hidden border border-gray-850',
  confidenceBarInner: 'h-full bg-gradient-to-r from-blue-500 to-indigo-500 rounded-full',
  applyBtn: 'w-full py-3.5 bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-500 hover:to-indigo-500 text-white font-semibold rounded-xl transition-all duration-300 shadow-lg shadow-blue-900/20 hover:shadow-blue-500/20 flex items-center justify-center gap-2 border border-blue-500/20 active:scale-[0.98]'
};
