export const sidebarStyles = {
  overlay: 'fixed inset-0 bg-background/80 backdrop-blur-sm z-[var(--z-modal)] lg:hidden',
  container: 'fixed top-0 bottom-0 left-0 w-[var(--sidebar-width-actual)] z-[var(--z-modal)] lg:z-[var(--z-sidebar)] lg:top-[var(--header-height)] bg-surface/30 backdrop-blur-xl border-r border-white/5 transition-all duration-300 flex flex-col',
  open: 'translate-x-0',
  closed: '-translate-x-full lg:translate-x-0',
  header: 'h-[var(--header-height)] flex items-center justify-between px-6 lg:hidden border-b border-white/5',
  logoText: 'text-2xl font-extrabold tracking-wider font-outfit text-white',
  closeButton: 'p-2 -mr-2 rounded-md hover:bg-surface text-text focus-visible:ring-2 focus-visible:ring-primary outline-none',
  nav: 'flex-1 overflow-y-auto py-6 px-4 space-y-1 relative',
  link: 'group relative flex items-center gap-3 px-3 py-3 rounded-xl font-medium transition-colors duration-300 outline-none focus-visible:ring-2 focus-visible:ring-primary text-text-muted hover:text-white',
  linkActive: 'text-white',
  activeIndicator: 'absolute inset-0 bg-primary/10 rounded-xl border border-primary/20 shadow-[inset_3px_0_0_0_rgba(0,242,254,1)]',
  icon: 'w-5 h-5 flex-shrink-0 transition-colors group-hover:text-primary relative z-10',
  iconActive: 'text-primary drop-shadow-[0_0_8px_rgba(0,242,254,0.8)]',
  linkText: 'relative z-10',
  footer: 'p-4 border-t border-white/5 flex flex-col gap-2',
  logoutButton: 'flex w-full items-center gap-3 px-3 py-3 rounded-xl font-medium transition-all duration-300 text-text-muted hover:bg-danger/10 hover:text-danger focus-visible:ring-2 focus-visible:ring-danger outline-none hover:-translate-y-0.5',
};
